name: CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install linters
        run: |
          npm init -y >/dev/null 2>&1
          npm i -D prettier eslint eslint-config-prettier
      - name: Prettier check
        run: npx prettier --check .
      - name: ESLint
        run: npx eslint .
