name: Format

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  prettier:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install Prettier
        run: |
          npm init -y >/dev/null 2>&1
          npm i -D prettier
      - name: Run Prettier write
        run: npx prettier --write .
      - name: Commit and push changes
        run: |
          if ! git diff --quiet; then
            git config user.name "github-actions[bot]"
            git config user.email "github-actions[bot]@users.noreply.github.com"
            git add -A
            git commit -m "chore: format with Prettier"
            git push
          else
            echo "No formatting changes."
          fi

